### ISSUE TITLE
Suggestion for 1st FPGA Training

### ISSUE THREAD

**Issue by GTS-Miller** [InnoIPA/EXMU-X261-usermanual#1]
1. Image跟Xmodels請放在GTS cross function資料夾
\02.Product\FPGA\EXMU-X261
![image](https://user-images.githubusercontent.com/114913625/194208082-c265b793-59bb-4f8b-ac46-539415242706.png)

2. Stesting請描述測試IO所需要接的Device或是Loopback治具
3. Stesting是否有一個 -all 的指令可以全功能測試
4. MicroUSB圖片標錯了
5. 錯字
6. 需要開一篇描述USB to UART的設定 (via putty)
7. GTS要練習
- 怎麼從SSH連進去FPGA做操作 (要知道哪些package要pre-install)
- 如何重燒emmc image (遠端無法透SSH燒入image)
- 修改開機位址到micro SD card.
- 如何更新某一個APP ex: vvas
- 進入OS後要怎麼確認每一個APP版本都是對的 (請在每一版BSP release note list出來) AKA Intel BKC (Best Known Configuration)

**Comment by Shaing** [comment]
fixed and improved at 0317067068dcd0b86245214ad7d7b623cfb7c4ae
